### ISSUE TITLE
Namespace in config and "ts" by default is confusing

### ISSUE THREAD

**Issue by danielzurawski** [szilveszter9/splunk-minimal-logger#2]
From the documentation
`// config -> { namespace: 'ns=something'  }`

Why not simply { namespace: 'something' }?
Also, as Splunk registers a timestamp against every message, why would you need to add your own one?

**Comment by szilveszter9** [comment]
these two issues have been resolved in version 2.0.0
the timestamp is optional now, nice to have if local servers' time and splunk's are not in sync
